sudo: false
language: scala
scala:
    - 2.11.12
    - 2.12.8
    - 2.13.0
env:
    - JDK=oraclejdk8
cache:
    directories:
        - '$HOME/.ivy2/cache'
sudo: false
before_script:
    - jdk_switcher use $JDK
matrix:
    # scala 2.12 requires java 8
    exclude:
        - scala: 2.12.8
          env: JDK=oraclejdk8
