sudo: false
language: scala
scala:
    - 2.10.6
    - 2.11.8
    - 2.12.1
env:
    - JDK=oraclejdk7
    - JDK=oraclejdk8
cache:
    directories:
        - '$HOME/.ivy2/cache'
sudo: false
before_script:
    - jdk_switcher use $JDK
matrix:
    # scala 2.12 requires java 8
    exclude:
        - scala: 2.12.1
          env: JDK=oraclejdk7
